### ISSUE TITLE
IMA scalability is currently limited

### ISSUE THREAD

**Issue by maugustosilva** [keylime/keylime#1167]
# Environment
 * OS / version: Ubuntu 22.04, but not relevant
 * Processor architecture: amd64, irrelevant
 * TPM Manufacturer: virtual, irrelevant
 * Keylime version: 6.5.1+
 * Important: database connection is MySQL, with large (100+) number of agents; IMA is turned on, and using "version 1" allowlists.

# Description

While running scaling experiments in our virtual cluster, we have detected multiple serious problems with the current IMA implementation. We are planning to describe the general problem here, then issue a series of PRs to patch the problems we *can* patch.

We have a production scenario with the following boundary conditions:
1) Our nodes have "real-world production-ready" filesystems, with a large number of executables/libraries (tens of thousands)
2) We are forced to use a "version 1" IMA allowlist (policy), with a large number (again, tens of thousands) <checksum>,<path> pairs. This currently results in a roughly 20 MiB file size
3) Given we are including the `boot_aggregate` on the allowlist, we have a scenario where each individual node will have its own allowlist.

In a nutshell, the center of the problem is that the IMA implementation of keylime makes no allowances handling allowlists on this scenario.

Specifically:

* On the `verifier` each process in charge of `agent` verification has to hit the database twice for each verification: once to get the `agent` data from `verifiermain` table, a second time to get the allowlist contents from `allowlists` table. For *every individual attestation* (which by the default happens once each 2 seconds), this process is repeated.
* In addition to that, API calls to ascertain the status of `agent` currently do pull the whole allowlist contents from the `allowlists` table, applies a `len()` call to it and then populate a single attribute called `allowlist_len`

Our scaling test runs 1500 agents running copies of Ubuntu 22.04, running "identity + mesaured boot" attestation (one quote every 2 seconds for every `agent`). This works perfectly fine, requiring 9 `verifiers` each handling ~ 180 agents.

When IMA is turned on, using the ~ 20 MiB "version 1" allowlist previously discussed, attesting each `agent` requires 10 MiBps of exclusive bandwidth from the `verifier` doing the attestation to the database server (MySQL in our case). In theory this would exhaust our 100Gbps network connection after 1000 deployed agents. However, we don't even come close to that. Our monitoring system issues API calls via the CLI `keylime_tenant -c bulkinfo` to assess the status of the system every so often, and after about 100 tenants have been activated, `bulkinfo` is no longer operational: the download time of the massed allowlists exceeds the REST timeout.

## Expected behavior vs. actual behavior

We expected to be able to run IMA at scale exactly as we ran measured boot attestation. Clearly, we cannot do this -- we are running into a bandwidth issue.

## Steps to reproduce problem
1. Set up a 1500 agent keylime system using a MySQL database as a backend.
2. Feed the database with a 20 MiB "version 1" allowlist, with one per `agent`.
3. Turn on IMA gradually and measure bandwidth use.

# Relevant logs

There are no real logs available, although one could build a graph of bandwidth measurement as a function of activated `agents`. The graph is perfectly linear and predictable based on the formula (num_agents x allowlist_size / attestation_frequency),
which works out in our case to 10 MiBps (80 Mbps) for each active `agent`.

**Comment by galmasi** [comment]
Supporting information measured on a 1500 node cluster. Basically, 5 gbps of network traffic for ~ 50 deployed agents. We cannot measure beyond 200 because `bulkinfo` breaks completely at that point.

The equivalent numbers for *identity* attestation shows 5 mbps for 100 activated agents; ~ 3 orders of magnitude less than IMA; even 1500 agents barely make 100 mbps of traffic, which barely meters on the 100gbps network.

![image](https://user-images.githubusercontent.com/2000776/200932930-30b9c099-979b-45a4-8e97-3fe86686ae2a.png)

**Comment by stefanberger** [comment]
> What can be the solution? Incremental attestation for IMA hashes?

We already have incremental attestation.

I haven't looked at the code but this here could be a way to relief stress on the db (I apologize already, the following is theory since I haven't looked at the code, but I see there are now named allowlists):

<theory>

Each allowlist should have a unique field in the database (a timestamp, a random number, a hash over the actual allowlist, an auto-increment field, whatever) that is updated whenever the allowlist changes.

Each verifier should have a map of the allowlists accessible via their names (as keys to the allowlist) and as a value there should be an object holding the allowlist along with the unique field from the database and timestamps when to re-check the database for an updated of the allowlist. Whenever an allowlist is to be used the object is queried. Every few seconds, this object, when queried for the allowlist, checks the timestamp for expiration and should go to the database and check the unique field associated with the allowlist and if it has changed load the allowlist from the database, otherwise just make the current allowlist available for verification. Every N seconds (60 seconds?) one could walk the whole map of allowlists and `purge()` the entries that haven't been updated in the last n second to get rid of potentially deleted or unreferenced allowlists and free up some memory. So in effect the verifier would hold all actively used allowlist from the last N seconds in memory. The object is more or less a proxy for the allowlist database table accesses.

</theory>

**Comment by galmasi** [comment]
By way of responding to @aplanas -- the problem, as @stefanberger also pointed out, is not that the IMA logs have to be retrieved from the agent[s]. Stefan's incremental load already does that mitigation, and the resulting traffic is trivial (although of course there is conceivably a "startup shock", but the present issue crowds it out so we cannot measure it YET).

The problem is that *each* agent downloads the relevant allow list from the database for *every* attestation. Traditional style allow lists -- which are nothing more than lists of filenames and hashes -- are large even for relatively "thin" distributions; there is just not much we can do about that. 

The discussion with @maugustosilva and @mdrocco we are having is what legitimate ways there exist to reduce the load on the database. Stefan's theory sounds likely, but I'd rather we take the time to study the code -- the urge to patch things up and proceed with scale testing is very strong with, and some degree of caution seems advisable. :) 

There are some obvious gimmies, though. Expect a PR sometime today to remove the allowlist downloads from the`bulkinfo` tenant command. That is a sad blunder IMHO -- bulkinfo forces the download of *every* allow list in the system just because the allow list size is part of the response structure. Beyond a certain size this *guarantees* that bulkinfo cannot function: the REST API timeout is hit. 

Since bulkinfo is a general query about the state of a cluster, we feel that it need not include any information about allow lists -- not at the cost of functionality.

**Comment by aplanas** [comment]
> The problem is that each agent downloads the relevant allow list from the database for every attestation. 

That makes the issue very clear, and provides sense to @stefanberger idea : ))

**Comment by maugustosilva** [comment]
@mbestavros @mpeters it is good that @stefanberger mentioned a "hash over the actual allowlist", because this is something that already had on the code of my future PR (as the index for the `verifier` cache). 

I would like to see at least two new fields on the `allowlists` table: `checksum` and `length` . The first will be used for the purposes of caching while the second should give an user which requests `agent` status info some good hint if an IMA policy is being used by a particular agent.

This last point is important, due to the fact that in the current implementation an IMA policy is **always** created (an "empty" one), even if there was not an `allowlist` and `excludelist` specified as CLI parameters on `keylime_tenant`

**Comment by stefanberger** [comment]
> @mbestavros @mpeters it is good that @stefanberger mentioned a "hash over the actual allowlist", because this is something that already had on the code of my future PR (as the index for the `verifier` cache).

That's great and I would wait for this hash to come along. In the meantime I do some dry exercises with an AllowlistDBProxy: https://github.com/stefanberger/keylime/commits/stefanberger/allowlist_db_proxy

**Comment by stefanberger** [comment]
Well, implanting this AllowlistBDProxy class in the code may be a challenge... 

What do these relationship statements setup / do and how do they influence queries or what do they influence?

https://github.com/keylime/keylime/blob/56e951a851b9a12a58fa473da94d1c1bf1415676/keylime/db/verifier_db.py#L28
https://github.com/keylime/keylime/blob/56e951a851b9a12a58fa473da94d1c1bf1415676/keylime/db/verifier_db.py#L58

**Comment by mbestavros** [comment]
@stefanberger Apologies for the delayed response, I've been traveling -

Those `relationship` statements represent a foreign key relationship between a specific agent and an allowlist stored in the separate `VerifierAllowlist` table (which you can see in that same `keylime_db.py` file. This came about as part of the Allowlist API work I did over the summer, which finalized the transition to that separate `VerifierAllowlist` table.

In effect, if Keylime performs a full `joinedLoad` call on an agent, you'll get not just the fields on the Keylime agent itself, but also the allowlist entry within the `VerifierAllowlist` table that gets linked at agent creation time.

Then, you could refer to the linked allowlist with something like `agent.ima_policy.ima_policy`. Or you could grab the name with `agent.ima_policy.name`. Effectively, `agent.ima_policy` acts as a full `VerifierAllowlist` object, with all its fields on it.

**Comment by stefanberger** [comment]
@mbestavros Thanks for the explanation. A `joinedLoad` didn't even seem necessary and a `noload` does prevent it from loading the `VerifierAllowlist` table.

**Comment by maugustosilva** [comment]
fixed by PR #1243
