### ISSUE TITLE
[question] stateless keylime

### ISSUE THREAD

**Issue by mslacken** [keylime/keylime#1429]
# stateless keylime agent
I am trying to integrate keylime with [warewulf](http://github.com/hpcng.warewulf) which is stateless bare metal provisioning system. That means that the content of PCR8 and PCR9 are known and even predetermined, but after reboot all content on the node is lost.

After some experiments I found out, that a node running the keylime agent needs following configuration files, so that it is recognized between reboots:
```
/etc/keylime/agent.conf
/var/lib/keylime/cv_ca/cacert.crt
/var/lib/keylime/server-cert.crt
/var/lib/keylime/server-private.pem
```
and
```
/var/lib/keylime/agent_data.json
```
I assume that the files `server-cert.crt` and  `server-private.pem` are the certificates of the client keylime client and so just have a misleading name. Can these files created beforehand?
Also its not clear for me what is in the file `agent_data.json`?

My biggest question is, that when I  register the client with `keylime_tenant -c add` the keys are transferred to the client under `/var/lib/keylime/secure`, but after a reboot and a successful verification of the client, the keys are not transferred again. 
So how can I re transfer the keys  after a successful verification of a rebooted node in an automatic way?

**Comment by stefanberger** [comment]
> but after reboot all content on the node is lost.

Are you running this node from an iso without any hard disk where you could possibly store files? So nothing at all can be stored?

agent_data.json holds the key used for attestation. If this file is removed a new one will be created upon agent restart and this new file will contain a new key and the signature will not be recognized anymore on the receiving end. So you would have to preserve this file. Is there any way you can preserve files from such a node, like put them into a password protected archive that you HTTP PUT somewhere and retrieve it after reboot and before agent start? 

Once the node reboots you will have to use the tenant tool to kick off the attestation again which you could do with a `-c update`. Otherwise, if you cannot preserve anything I think you would have to do a `-c delete` followed by a `-c add`.

**Comment by mslacken** [comment]
> > but after reboot all content on the node is lost.
> 
> Are you running this node from an iso without any hard disk where you could possibly store files? So nothing at all can be stored?
>

The node boots over network (iPXE, but also grub with http in the future) and gets a static root image and an individual configuration overlay which can carry the keys and the `agent_data.json`. 

> agent_data.json holds the key used for attestation. If this file is removed a new one will be created upon agent restart and this new file will contain a new key and the signature will not be recognized anymore on the receiving end. So you would have to preserve this file. Is there any way you can preserve files from such a node, like put them into a password protected archive that you HTTP PUT somewhere and retrieve it after reboot and before agent start?
> 

I can keep the file in the configuration overlay, but this file will be transferred unencrypted to the node.
So do you know how `agent_data.json` and the files `server-cert.crt` and `server-private.pem` relate together?

> Once the node reboots you will have to use the tenant tool to kick off the attestation again which you could do with a `-c update`. Otherwise, if you cannot preserve anything I think you would have to do a `-c delete` followed by a `-c add`.

The whole idea is to remotely attest PCR8 and PCR9 and then start a secured and authenticated communication with the node over a client service.

**Comment by ansasaki** [comment]
> I assume that the files `server-cert.crt` and `server-private.pem` are the certificates of the client keylime client and so just have a misleading name. Can these files created beforehand?

The `server-cert.crt` and `server-private.pem` are the keylime agent server TLS certificate and private key, so they don't have a misleading name. You can create them beforehand. You can configure the files to be used by setting the `server_cert` and `server_key` options in `/etc/keylime/agent.conf` or (recommended) dropping a configuration snippet file in `/etc/keylime/agent.conf.d`, containing something like:
```
[agent]
server_key = "/path/to/agent/key"
server_cert = "/path/to/agent/cert"
```

Alternatively, you can override the configuration by setting the `KEYLIME_AGENT_SERVER_CERT` and `KEYLIME_AGENT_SERVER_KEY` environment variables. In fact, you can override any configuration option by setting the respective environment variable composed by `KEYLIME_AGENT_` prefix followed by the configuration option in upper case separated by `_`.

> Also its not clear for me what is in the file `agent_data.json`?

It contains the AK key associated with the EK key from the TPM. It is stored to avoid re-generating a new key every time the keylime agent is restarted. You can configure the path where this data is stored by setting the `agent_data_path` option in the configuration or by setting the `KEYLIME_AGENT_AGENT_DATA_PATH` environment variable.

As @stefanberger wrote above, if you do not keep the `agent_data.json` between restarts of the keylime agent, you have to delete and add back the agent as a new key will be generated.

The `agent_data.json` is unrelated with the `server_key` and `server_cert`.

**Comment by mslacken** [comment]
@stefanberger @ansasaki thanks a lot for your help.
As far as I understand now, I just need to preserve the data in `agent_data.json` as its tied to the TPM of the node
The `server-cert.crt` certificate and private key `server-private.pem`  are newly generated  if they are missing, at least for `rust-keylime-0.2.1`.

**Comment by ansasaki** [comment]
> As far as I understand now, I just need to preserve the data in `agent_data.json` as its tied to the TPM of the node
> The `server-cert.crt` certificate and private key `server-private.pem` are newly generated if they are missing, at least for `rust-keylime-0.2.1`.

When the agent registers itself with the registrar, it sends the `server-cert.crt` which is stored in the registrar database. The other components get this certificate from the registrar when they need to contact the agent.

On restart, the agent will re-generate the key and certificate which will not match with what the registrar received in the previous run. You will not se an error until one of the components try to reach the agent and fails to verify its certificate on TLS handshake.

If you are willing to delete/add the agent on each restart, then it is fine to not keep any data as everything will be re-generated. Otherwise, if you want to keep the agents identities, you will need to store all (key, cert, and the agent_data).

**Comment by mslacken** [comment]
@maugustosilva The nodes are going through a dedicated on boarding process , but this automatic process.
Do you know how to tie the identity of the node to the TPM's EKs and EK cert?

**Comment by stefanberger** [comment]
> Do you know how to tie the identity of the node to the TPM's EKs and EK cert?

The EK cert is issued by the TPM manufacturer and the EK key itself is NOT a signing key but a storage key and therefore won't sign you any certificates that related to keys that are inside the TPM and could be used for TLS connections. So there would have to be some scheme that involves keys that a verifiable to be inside the TPM, such as attestation keys that are setup using makecredential/activatecredential where (I think) the verifier side should run the makecredential part to witness the trustworthiness of the key that's going to be use for TLS and that the key is inside a TPM. It sounds quite a bit more involved to setup this kind of key and then to teach the TLS stack to use the key inside the TPM rather than a software key...

**Comment by maugustosilva** [comment]
> @maugustosilva The nodes are going through a dedicated on boarding process , but this automatic process. Do you know how to tie the identity of the node to the TPM's EKs and EK cert?

What we do in our production environment is, upon receiving a new node, booting once (which has to be done anyway for acceptance/health/validation checks) and extracting the EK from the TPM. From this point on, whenever an `agent` has to be added to a `verifier`, the `tenant` executes the `ek_check_script` to make sure that a particular EK is on the "approved list". Please note, as @stefanberger just mentioned, the tying up of the EK with AIK (which is effectively used by all `keylime` operations) is made by the "makecredential/activatecredential" on the `registrar`.

IMO, identifying an `agent` by its TLS certificates makes sense basically in an IoT environment, where new, not previously inventoried hardware devices/nodes, can "appear" dynamically.
