### ISSUE TITLE
Error when using HTTPs RESTful APIs to access keylime registrar with curl

### ISSUE THREAD

**Issue by Jingshui1037** [keylime/keylime#1439]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

No

# Environment

 * Keylime version: master 

# Description 

When I use https RESTful APIs to access the keylime registrar with curl,  there is an error that `tlsv13 alert certificate required, errno 0`.

The steps to reproduce problem and relevant logs are as followings. What should I do to fix this problem? 

## Steps to reproduce problem

```shell
curl --cacert /var/lib/keylime/server-cert.crt -k --key /var/lib/keylime/server-private.pem -v  "https://127.0.0.1:8891/v2.1/agents"  | jq .
```

# Relevant logs

Attach any relevant log files that can help to debug your issue. 

- curl logs:

![image](https://github.com/keylime/keylime/assets/135581562/6f226f0b-313b-4dda-83b7-006c4e83708b)

- keylime registrar logs:
![image](https://github.com/keylime/keylime/assets/135581562/160b0087-0ec3-4d12-bf27-dc6ed3856577)

**Comment by ansasaki** [comment]
@Jingshui1037 Hello, could you please try removing the `-k` option from the curl command? The `-k` option (equivalent to `--insecure`) makes the client to not provide its certificate.

And also you should be using the client certificates for your client, and not the server certificates. Try with something like:
```
curl --cacert /var/lib/keylime/cv_ca/cacert.crt --key /var/lib/keylime/cv_ca/client-private.pem --cert /var/lib/keylime/cv_ca/client-cert.crt -v  "https://127.0.0.1:8891/v2.1/agents"  | jq .
```

**Comment by THS-on** [comment]
You still need the `-k` because hostnames are validated in curl otherwise and I think there is a option to only disable that. As @ansasaki pointed out the client certificate is still needed. Something like this works:

```
curl  --key /var/lib/keylime/cv_ca/client-private.pem --cert /var/lib/keylime/cv_ca/client-cert.crt -k  "https://127.0.0.1:8891/v2.1/agents"  | jq .
```

**Comment by Jingshui1037** [comment]
Thanks @THS-on , I succeed when I used your command. This is my test result.

![image](https://github.com/keylime/keylime/assets/135581562/cc183331-6085-412a-aba1-5b05bd88ab79)

**Comment by Jingshui1037** [comment]
Now I close this issue. Thanks @THS-on @ansasaki

**Comment by Jingshui1037** [comment]
Hi @THS-on @ansasaki,

Now I can succeed to use HTTPs RESTful APIs to access keylime registrar and keylime verifier with curl according to your command. However, when I use the curl command to access keylime agent with HTTPs RESTful APIs, there is an new error like the following.  What should I do to fix this problem?

```shell
curl --key /var/lib/keylime/cv_ca/server-private.pem --cert /var/lib/keylime/cv_ca/server-cert.crt -k  https://127.0.0.1:9002/v2.1/version -v | jq .
```
![image](https://github.com/keylime/keylime/assets/135581562/df018931-5821-4091-933c-7d6b5807aab3)

**Comment by ansasaki** [comment]
@Jingshui1037  Please provide the logs from the agent. You can get them by running the agent with the `RUST_LOG` environment variable set like `RUST_LOG=keylime_agent=debug keylime_agent`

I'd say there is a fair probability that the agent don't have access to the CA certificate generated by the verifier in `/var/lib/keylime/cv_ca/cacert.crt`. If that is the case, you need to `chown` to provide access to the user running the agent.

**Comment by Jingshui1037** [comment]
Thanks @ansasaki ,

These are the logs of my keylime agent in the first picture below. And when I `chown`  those three files (`/var/lib/keylime/cv_ca/cacert.crt`, `/var/lib/keylime/server-cert.crt` , and `/var/lib/keylime/server-private.pem`) to `keylime:tss`  according to your suggestion in the second picture below, the error changes to `error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca` in the last picture below.
 
![image](https://github.com/keylime/keylime/assets/135581562/b0ce3afb-1ca4-45b4-8eb0-e2434ed69104)

![image](https://github.com/keylime/keylime/assets/135581562/9a37876b-6b6f-4291-80cf-da97ec0f249a)

![image](https://github.com/keylime/keylime/assets/135581562/3fc423c7-80e2-4d5d-aff1-9896531b8e28)

**Comment by ansasaki** [comment]
@Jingshui1037 OK, then the last issue is that you have to provide the agent certificate in the `--cacert` option. Differently from the other components, the agent generates a self-signed certificate, so it is not signed by the CA certificate from `/var/lib/keylime/cv_ca/cacert.crt`.  

Also, you should not be using the certificates generated by the agent as your client's certificate. Use the ones generated by the verifier from `/var/lib/keylime/cv_ca` instead. Try:

```
curl  --key /var/lib/keylime/cv_ca/client-private.pem --cert /var/lib/keylime/cv_ca/client-cert.crt --cacert /var/lib/keylime/server-cert.crt -k  "https://127.0.0.1:9002/v2.1/version" -v  | jq .
```

**Comment by Jingshui1037** [comment]
@ansasaki , according to your suggestion, I find a problem the agent machine doesn't have those two files(`/var/lib/keylime/cv_ca/client-private.pem`、`/var/lib/keylime/cv_ca/client-cert.crt`). So I have to copy these files from the keylime registrar machine and `chown` them to `keylime:tss`.

![image](https://github.com/keylime/keylime/assets/135581562/a22f01c4-de58-48ef-9dc9-8148e136aeca)

Then I use the command you provided to access the agent, the error logs change to 
`error:1409441B:SSL routines:ssl3_read_bytes:tlsv1 alert decrypt error` which is similar to the first issue about my agent above

![image](https://github.com/keylime/keylime/assets/135581562/419a0b33-7a48-48ec-aa00-a9ab9c04d341)
 
So I'm still confused about which private key and cert should I use.

**Comment by ansasaki** [comment]
> @ansasaki , according to your suggestion, I find a problem the agent machine doesn't have those two files(`/var/lib/keylime/cv_ca/client-private.pem`、`/var/lib/keylime/cv_ca/client-cert.crt`). So I have to copy these files from the keylime registrar machine and `chown` them to `keylime:tss`.

Right, the agent machine will not have those files because the verifier is responsible for generating them by default. If you are running the components in different machines, then some provision steps are needed as the default configuration assumes you are running all the components in the same machine (for testing).

By default, he verifier will create a mini CA and generate key pairs and respective certificates for the server role and client role. They are placed in `/var/lib/keylime/cv_ca/` in the verifier machine.

- The verifier needs the server keys for its REST API server, as well as the client keys to access the other components (registrar and agent)
- The registrar only needs the server keys and certificate as it does not access other components as clients
- The tenant needs only the client keys and certificate as it does not act as a server

All these certificates are signed by the same verifier mini CA.

For the agent, it is different. The agent generates its own self-signed certificate to use as its server TLS certificate (the so-called mtls certificate)

- The agent needs only server keys and certificate because when acting as a client (to access the registrar) it does not use any certificate (TLS is not used for this connection)
- BUT it needs the CA certificate for the clients it trusts (configured via the `trusted_client_ca` in the config file) to verify the clients in the incoming connections. It means you need to provide the CA certificates that signed the certificates of all clients that are accessing the agent (tenant and verifier, or in your case `curl`).

In the default case, the verifier will generate all the certificates and put in `/var/lib/keylime/cv_ca`. The agent, by default, uses the CA certificate from that location (`/var/lib/keylime/cv_ca/cacert.crt`).

You need to copy the CA certificate from the verifier and put in `/var/lib/keylime/cv_ca/cacert.crt` in the agent machine. Alternatively, you can copy it to some location the user running the agent process can access and configure the path in the `trusted_client_ca` configuration option. If you are using different CAs for the components, you need to provide all of them as a list. For example, in the agent machine, add a configuration snippet file in `/etc/keylime/agent.conf.d/` containing:

```
[agent]
trusted_client_ca = "['/path/to/a/CA/certificate', '/path/to/another/CA/certificate']"
```

Alternatively you can override the agent configuration option by setting the `KEYLIME_AGENT_TRUSTED_CLIENT_CA` environment variable. Something like:

```
$ RUST_LOG=keylime_agent=debug KEYLIME_AGENT_TRUSTED_CLIENT_CA="['/path/to/a/CA/certificate', '/path/to/another/CA/certificate']" keylime_agent &
```

then, in the curl command you need to provide the client certificate (signed by one of the CA certificates you provided in the agent configuration) and key:
```
curl  --key /var/lib/keylime/cv_ca/client-private.pem --cert /var/lib/keylime/cv_ca/client-cert.crt -k  "https://127.0.0.1:9002/v2.1/version"  | jq .
```

**Comment by Jingshui1037** [comment]
@ansasaki , Thank you very much for your detailed reply, now I understand it and can succeed to access agent with curl and HTTPS RESTful APIs.

![image](https://github.com/keylime/keylime/assets/135581562/27ddbfaa-d367-4cc3-99b0-f5163621e8c3)

Now I close this issue.
