### ISSUE TITLE
`keylime_policy` claim to support `sm3_256` digest algorithm, but does not 

### ISSUE THREAD

**Issue by ansasaki** [keylime/keylime#1609]
Is your issue a feature request? If so, please raise it as an [enhancement](https://github.com/keylime/enhancements)

# Environment
 * OS / version: N/A
 * Processor architecture: N/A 
 * TPM Manufacturer: N/A
 * Keylime version: current master (dc118c780a06cb72725f72bc8100665a07a5a12f)

# Description 
`keylime_policy create runtime --help` shows that the `sm3_256` algorithm is supported, but it fails when it is provided.
The unsupported algorithm should be dropped.

## Expected behavior vs. actual behavior

Actual:

`keylime_policy create runtime --help` shows in the `--algo` option the choices `{sha1,sha256,sha384,sha512,sm3_256}`

When running the policy generation with the `sm3_256` algorithm, an error is generated, similar to:

`2024-08-08 08:11:23.399 - policy.create_runtime_policy - ERROR - Base policy is not a valid runtime policy: 'sm3_256' is not one of ['sha1', 'sha256', 'sha384', 'sha512']`

Expected:

`keylime_policy create runtime --help` shows in the `--algo` option only the supported choices `{sha1,sha256,sha384,sha512}`

## Steps to reproduce problem
1. Run '`keylime_policy create runtime --rootfs some_dir --algo sm3_256`'

# Relevant logs
An error similar to the following is returned

`2024-08-08 08:11:23.399 - policy.create_runtime_policy - ERROR - Base policy is not a valid runtime policy: 'sm3_256' is not one of ['sha1', 'sha256', 'sha384', 'sha512']`

**Comment by marcostork** [comment]
The quick fix is to set `log_hash_alg` to `sha1`. I couldn’t test the resulting policy because my kernel wouldn’t load IMA with sm3_256, but the resulting hashes are sound.
Keylime accepts `["sha1", "sha256", "sha384", "sha512"]` as the template hash algorithms, so the IMA module is refusing `sm3_256`. However, the real problem is that keylime_policy sets `log_hash_alg` to the file content hash algorithm, while Keylime expects to receive the template hash.
I believe the best approach right now is to set `log_hash_alg` to `sha1`, as the [Keylime Documentation](https://keylime.readthedocs.io/en/latest/user_guide/runtime_ima.html#runtime-policy-json-schema) mentions it is hardcoded to `sha1`, even though the policy is a filedata hash and the only hash algorithm shown will be the template hash.
If it is acceptable, I will proceed with the fix.

**Comment by ansasaki** [comment]
Just to add the information that the algorithm `sm3_256` is actually supported by IMA for the file data hash and by the `keylime_policy` , therefore this issue was actually invalid.

See the IMA documentation for the `d-ng` [Hash Algorithm](https://ima-doc.readthedocs.io/en/latest/event-log-format.html#hash-algorithm) and the supported algorithms that can be used as the `ima_hash` [parameter when booting the kernel](https://ima-doc.readthedocs.io/en/latest/ima-configuration.html#ima-hash)
