### ISSUE TITLE
Add `agent_id` to revocation message

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#238]
The `agent_id` would be a useful piece of metadata to provide in revocation messages.

**Comment by nabilschear** [comment]
wow, i thought for sure that it was in there, but it's not.  

However, there is a feature where the tenant can provide whatever metadata they want and it will get passed.  We use this to set the certificate serial number that should be revoked.  See https://github.com/keylime/keylime/blob/68580626b7c2887ff2cbb18ab2a37edba54cf6eb/keylime/tenant.py#L371 and then it gets used here: https://github.com/keylime/keylime/blob/68580626b7c2887ff2cbb18ab2a37edba54cf6eb/keylime/ca_util.py#L394

**Comment by lukehinds** [comment]
Interesting, thanks @nabilschear - my only thought here is, would this not require editing the keylime code to add the extra needed values? Or am I missing away a user can parse in the values which are then handed to revocation?

**Comment by lukehinds** [comment]
Trying to figure out how that works, so the tenant tells the verifier - include this field in the revocation event. I am confused as it looks like its going into the payload, which gets sent to the agents?

**Comment by nabilschear** [comment]
yes, the tenant can say, please include this additional info if this node gets revoked.  Then the agents or anyone else who listens to the revocation message can act on that additional info.  this is kinda the crux of how revocations can be useful.  because you need some information about what to do with the revocation, which is application specific.
