### ISSUE TITLE
Support more IMA hashing algorithms (TPM 2.0)

### ISSUE THREAD

**Issue by jetwhiz** [keylime/keylime#30]
Keylime currently only supports SHA1 with IMA, particularly since IMA's template_hash field only supports SHA1 (though the Linux kernel extends this SHA1 value into all available hashing algorithms).  Add support for additional algorithms for IMA. 

See (for example): 
* https://github.com/mit-ll/python-keylime/blob/master/keylime/tpm_abstract.py#L345
* https://github.com/mit-ll/python-keylime/blob/master/keylime/ima.py
* https://github.com/mit-ll/python-keylime/blob/master/keylime/ima_emulator_adapter.py

**Comment by lukehinds** [comment]
Just been looking into this @jetwhiz 

On the face of it, it makes sense (sha1 is not collision proof), but I am also aware sha1 is default and a lot of Linux Distributions are running with sha1 as the kernel compiled option:

```
cat /boot/config-$(uname -r) |grep CONFIG_IMA
CONFIG_IMA=y
CONFIG_IMA_MEASURE_PCR_IDX=10
CONFIG_IMA_LSM_RULES=y
# CONFIG_IMA_TEMPLATE is not set
CONFIG_IMA_NG_TEMPLATE=y
# CONFIG_IMA_SIG_TEMPLATE is not set
CONFIG_IMA_DEFAULT_TEMPLATE="ima-ng"
CONFIG_IMA_DEFAULT_HASH_SHA1=y
# CONFIG_IMA_DEFAULT_HASH_SHA256 is not set
CONFIG_IMA_DEFAULT_HASH="sha1"
CONFIG_IMA_WRITE_POLICY=y
CONFIG_IMA_READ_POLICY=y
# CONFIG_IMA_APPRAISE is not set
CONFIG_IMA_KEYRINGS_PERMIT_SIGNED_BY_BUILTIN_OR_SECONDARY=y
```

Is it a case of SHA1 is not "insecure" per say with IMA (perhaps because its an extension of lots of hashses).

Put this way, if someone makes an issue or pulls us up at a conference and says 'you're using SHA1 and that's dangerous" can we say 'yes we agree' or is it a case of no risk is there as collisions are not a factor in sha1's use in IMA and tpm quotes?

**Comment by jetwhiz** [comment]
I don't think setting these variables to use `sha256` would fix the problem that's discussed in this issue.  

There are actually two separate hash algorithms / digests used in IMA.  The template hash/digest and the file hash/digest.
https://sourceforge.net/p/linux-ima/wiki/Home/#ima-measurement-list

The `CONFIG_IMA_DEFAULT_HASH_SHA256` and `CONFIG_IMA_DEFAULT_HASH` variables are likely setting the default for the file hash and not the template hash, if I'm interpreting the context of that code correctly.  

As far as I know, IMA itself does not support anything other than SHA1 for the template digest.  The Linux kernel, however, will extend this SHA1 hash into all available PCR banks (for TPM2), padding remaining bits with 0's for hashing algorithms larger than SHA1 (https://www.fclose.com/linux-kernels/726319/tpm-enhance-tpm-2-0-pcr-extend-to-support-multiple-banks-linux-4-11/).  

From a Keylime perspective, we can use the sha256 PCR bank (for instance) instead of SHA1 for the extended hash over all files, though each underlying file is still using SHA1 under the hood for its template digest.
