### ISSUE TITLE
Non monitoring Agent

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#326]
This will likely be an enhancement proposal. Logging an an initial issue here.

The idea is to run an agent on a machine, with no TPM, yet still capable of accepting revocation events.

**Comment by nabilschear** [comment]
there's already a skeleton of this in the keylime ca.  the "listen" functionality essentially does this: https://github.com/keylime/keylime/blob/89e2ffb55829ea3af7cb602b7df90e43d23372e1/keylime/ca_util.py#L338  but we'd need to expand that to execute some set of revocation actions (instead of being hard wired to revoke certs)

**Comment by lukehinds** [comment]
Very handy, thanks @nabilschear !

**Comment by mpeters** [comment]
I've worked around this in the past by just having an exclude list that includes everything. But you still have to set up the tpm, ima, etc just to have it all ignored. Would be nice to have as a real feature

**Comment by mpeters** [comment]
Would it also be possible for this agent (and others) to receive events when a new nodes is approved? This would be useful for things like: make sure a host is monitored by keylime before it is put into a k8s cluster. We have the ability to remove a node from a cluster that fails, but nothing to tell some bootstrapping system it's time to add a node.

**Comment by THS-on** [comment]
Now that we have webhook support for external systems, is this issue still relevant?

**Comment by mpeters** [comment]
Probably not. I think webhooks are a cleaner solution than something that can do even more code execution.
