### ISSUE TITLE
Modified the files in whitelist.txt, the checking continues

### ISSUE THREAD

**Issue by Epiphyll** [keylime/keylime#421]
#Environment
 * OS / version: Centos 7
 * Processor architecture: 
 * TPM Manufacturer: TPM emulator
 * Keylime version: 5.7.3

# Description 
I succeeded in running keylime，like this
![keylime](https://user-images.githubusercontent.com/22440504/100563459-62c11a80-32f9-11eb-8c94-814f854511a7.png)

If I run a script not included in the whitelist.txt, the agent will fail, but I modified the agent file /etc/hostname included in the whitelist.txt, keylime_verifier was Checking continues, the agent didn't fail, Is there anything wrong with my operation?

**Comment by lukehinds** [comment]
Ah this might be down to the `/etc/ima/ima-policy` file - the standard ima policy will only measure files when they make a sys call for execution. Let's say for example we have a script called acme.sh, we can change that and keylime with its current ima policy won't react until you execute that script - at that point the script file will be measured and compared to the allowlist. 

@stefanberger would you happen to know if there is an `ima-policy` entry that would measure a file write?

**Comment by stefanberger** [comment]
@lukehinds As far as I know the default IMA policy doesn't measure file writes.

**Comment by Epiphyll** [comment]
@lukehinds If I change the ima-policy, do I need to change the create_whitelist.sh code?

**Comment by lukehinds** [comment]
> @lukehinds As far as I know the default IMA policy doesn't measure file writes.

would mimi or anyone know what entry would enable this (if its possible)?

**Comment by lukehinds** [comment]
> @lukehinds If I change the ima-policy, do I need to change the create_whitelist.sh code?

No, that won't require different hashes.

**Comment by Epiphyll** [comment]
Hi friend @lukehinds , In my point of view I think files in the whitelists are continually measured by Keylime verifier. Is the local measurement on the client side done through ima or keyime client? I'm using the demo ima-policy, but it seems that files in the whitelists are not monitored. I want to know how to enable the file monitor. Do I need to change the ima-policy?

**Comment by mpeters** [comment]
Yes @Epiphyll  IMA is what actually measures the files and puts them into the log which keylime reads. The usual default for IMA is to only check files as they are being executed (or loading code in an executable like lib files). If you want it to change to every file that is written then you need to change your ima-policy and you'll have to look at the IMA documentation for that. Also be careful because if your system is busy writing a lot of files (like log files) you need to make sure you don't have IMA doing a lot of busy work measuring those files or it will slow down your host.

**Comment by stefanberger** [comment]
If a file that was written to is not measured _when it is read again_ than this may either be due to the IMA policy or may be due to how the filesystem is mounted. For the latter please have a look at the documentation here: https://sourceforge.net/p/linux-ima/wiki/Home/

The section in the IMA docs of relevance is this one here: https://sourceforge.net/p/linux-ima/wiki/Home/#ima-re-measuring-files

You may have to remount your filesystems using a command like this one here:
```
su -c 'mount -o remount,rw,iversion /home'
```
The `iversion` is the important parameter. Alternatively add this _carefully_ to your `/etc/fstab` [4th column I would say].

Once it remeasures such (mutable) files (assuming now the IMA policy measures all files on read) you may need to consider adding this file to the exclude list. If you want this file to be considered immutable then the verification failure on repeated modifications to this file could be considered good of course.

**Comment by lukehinds** [comment]
I will close this for now, you can re-open if its still unanswered @Epiphyll
