### ISSUE TITLE
docker script error

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#537]
Opening this for a user who sent it to the keylime list

I tried to run the docker environment, but facing a problem when selecting the option for tpm 1.2 or tpm2.0. When selecting a or b i am getting error

"/bin/bash: /root/keylime/.ci/test_wrapper.sh: no such file or directory
failed to resize tty, using default size"

it would be great if you can help.

**Comment by THS-on** [comment]
The scripts on how to run the local container for testing have changed with https://github.com/keylime/keylime/commit/3163e3d99fbdd4e381aa61a42bc586aad6a97bea and are pretty robust. The only thing to remember is to set `KEYLIME_REPO_PATH` to the right directory.

@lukehinds do you think this issue is still relevant?
