### ISSUE TITLE
AK authorizations in `tpm2_activatecredential` (was lUpdate tpm2-tools references)

### ISSUE THREAD

**Issue by lukehinds** [keylime/keylime#59]
Now that @jetwhiz tpm2-tools patches have landed upstream we can change git repo URLs from /keylime/tpm2-tools to /tpm2-software/tpm2-tools

**Comment by jetwhiz** [comment]
Unfortunately this isn't possible to do yet, since there is still a bug upstream with AK authorizations in `tpm2_activatecredential` which Keylime relies on.  The older pre-ESAPI version works, which is what the [keylime/tpm2-tools](https://github.com/keylime/tpm2-tools) is based on.  

Another thing to do before switching repositories is that `tpm2_deluxequote` was basically renamed to `tpm2_quote` in the patches upstream, so that change will need to be made (namely in tpm2.py, such as here: https://github.com/keylime/python-keylime/blob/master/keylime/tpm2.py#L723) before switching.

**Comment by lukehinds** [comment]
Thanks Charlie, I figured as much. Let's keep this for tracking when the above points are resolved.

**Comment by lukehinds** [comment]
@jetwhiz , do you have the upstream bug number for AK auth issues in `tpm2_activatecredential`?

**Comment by jetwhiz** [comment]
It seems like this is a generic issue affecting many different tools under the ESAPI, so I'm not sure what this would fall under.  So far this has just been discussed on the mailing list: https://lists.01.org/pipermail/tpm2/2019-February/001046.html.

**Comment by jetwhiz** [comment]
This still needs to be done after upstream issue fixed: https://github.com/tpm2-software/tpm2-tools/issues/1453

**Comment by jetwhiz** [comment]
Note that these issues have now been fixed upstream, as of [PR#1513](https://github.com/tpm2-software/tpm2-tools/pull/1513) and [PR#1499](https://github.com/tpm2-software/tpm2-tools/pull/1499).  

Do we want to switch to using tpm2-tool upstream's `master` branch, or stick with our fork?  Note that their `master` branch changes very frequently (including their tool APIs) and we may need to be doing fixes often to keep Keylime in sync with their `master` branch. 

We could also have their `3.X` ("legacy") branch be our default that we target instead of master, though this will rely on https://github.com/keylime/keylime/issues/123 being completed.

**Comment by lukehinds** [comment]
Good point. I definitely think master and include 3.x tests as well 

Hoping I can bury this py3 port soon and this CI installation updates will be next on the list.

**Comment by jetwhiz** [comment]
Just as a note, it is very likely a recent update in the upstream tpm2-tools `master` branch has broken keylime functionality.  In particular, this commit: https://github.com/tpm2-software/tpm2-tools/commit/f8b528bbe735a0e3db758115649662f39a85673c#diff-f7f2fb4b9af4897ea452e93077a35814

Using `tpm2_activatecredential` has become a bit more complicated now, so we will have to fix this at some point if we want to target master (instead of `3.X`).

**Comment by lukehinds** [comment]
> Just as a note, it is very likely a recent update in the upstream tpm2-tools `master` branch has broken keylime functionality. In particular, this commit: [tpm2-software/tpm2-tools@f8b528b#diff-f7f2fb4b9af4897ea452e93077a35814](https://github.com/tpm2-software/tpm2-tools/commit/f8b528bbe735a0e3db758115649662f39a85673c#diff-f7f2fb4b9af4897ea452e93077a35814)
> 
> Using `tpm2_activatecredential` has become a bit more complicated now, so we will have to fix this at some point if we want to target master (instead of `3.X`).

Is this something we should raise an issue in upstream in tpm2-tools - I am concerned this is going to just bite us one day so we should get this flagged somehow.

**Comment by jetwhiz** [comment]
The changes they've made upstream work correctly (they're just making the activatecredential tool more flexible), but we need to make sure that we update Keylime to reflect these changes in the tools.  They've likely also made other changes since I last checked that break Keylime against upstream `master`.  

Since `master` changes rapidly upstream, this will be an ongoing effort to keep Keylime compatible with the upstream tools.
