### ISSUE TITLE
Maintaining documents in the keylime repo

### ISSUE THREAD

**Issue by kaifeng** [keylime/keylime#623]
Propose to merge keylime documentation repo to the keylime repository, this move will helps we maintain document update with code changes more conveniently.

**Comment by maugustosilva** [comment]
I strongly support this proposal. After several months contributing code to keylime, I observe that the effect o having documentation on a separate repository on me is to make me less likely of updating documentation pari passu with the changes on the code.

**Comment by lukehinds** [comment]
We could do this if it meant folk actually bothering to document their changes (I am sceptical to be honest). Otherwise we are just rearranging the furniture, but the underlying problem still remains.

**Comment by mpeters** [comment]
I think this would be a good change because there have been times I've wanted to hold off on merging something until it was documented. But I can't really do that as they are in 2 separate repos and that would mean documentation would have to land before code which isn't terrible, but a bit harder to coordinate.

With this change we could simply withhold merging something until the documentation is also part of the PR.

**Comment by THS-on** [comment]
I'm supporting this change. I've now written my own tenant implementation and the current API documentation was not really helpful so I updated it.
If now more systems interact with Keylime we should have an up-to-date documentation for easier integration. Also the crypto and key derivation parts should be documented somewhere outside the original paper.

**Comment by THS-on** [comment]
The change is done with https://github.com/keylime/keylime/pull/1018
