### ISSUE TITLE
Why does keylime_webapp get a list of registered agents from keylime_registrar every time?

### ISSUE THREAD

**Issue by MartinMa28** [keylime/keylime#628]
Quick question here:

In keylime_webapp, basically, it's doing something below periodically:
1. Call keylime_registrar to get a list of registered agent UUIDs
2. Call keylime_verifier for every agent UUID in the list to get the details of such agent

My question is why do we need to call registrar every time? Is it because some records in verifier's DB might not be considered as a registered agent anymore? If it is, why some records in verifier's DB are not registered anymore? Can't we delete them from verifier's DB and then simply get all records in verifier's DB and display them on the GUI?

**Comment by mpeters** [comment]
When an agent comes online it tries to contact it's configured registrar. The registrar gets information about that host and stores it in it's db. Later when someone runs the `keylime_tenant` command they provide information about a host that is know to the registrar along with information about how to attest that host (things like IMA policy, exclude list, measured boot policy, etc). Then the verifier can start doing attestation.

So it's useful to know what hosts are known to the registrar but haven't started attestation yet, hence are unknown to the verifier.

**Comment by nabilschear** [comment]
in terms of why the UI does this.  It was a user-experience thing.  Here's how many machines keylime knows about (because registration happens on boot). Another clarification: at some point long ago the registrar and verifier used to be the same service.  We split them apart because you may end up having multiple registrars (if you're doing vTPMs).  But this separation isn't super important.  They are equally important in the security architecture.

**Comment by kgold2** [comment]
"registration happens on boot" ... on first boot or every boot.  Assuming registration means generating a certificate for the attestation key, it is presumably once per tenant.

As for separation, the opposite may be true.  There may be one registrar, with it's CA private key behind firewalls, with an HSM, locked room, etc.  There could be multiple verifiers, with less protection because they don't have private keys.
