### ISSUE TITLE
Re-activate agent on server puts it to state 3 for some period of time

### ISSUE THREAD

**Issue by bartpastuszkaTE** [keylime/keylime#697]
# Description 
A disabled Keylime agent have operational state 7 (FAILED) and after the agent starts should be reactivated on Keylime server side, but if agent is stopped and you try to re-activate it on server the operational state becomes 3 (GET_QUOTE) for some time (~10 sec) and then get back to 7. State 3 is trusted, so this is undesirable behavior if an agent is stopped

## Expected behavior vs. actual behavior 
Expected behavior: a stopped Keylime agent doesn't have state 3 (GET_QUOTE) at all
Actual behavior: a stopped Keylime agent has state 3 for some time after a reactivation

## Steps to reproduce problem
1. Stop Keylime agent and wait some time
2. Try to reactivate it on a server
3. Check current state
4. Wait ~10 sec
5. Check state

# Relevant logs
`keylime_tenant -v 21.110.0.1 --cert /var/lib/keylime/cv_ca -c reactivate -u 37383638-3330-5a43-3239-343530315734
`

**Comment by bartpastuszkaTE** [comment]
I already have prepared 2 fix proposals

**Comment by bartpastuszkaTE** [comment]
please assign

**Comment by THS-on** [comment]
This behavior some somewhat expected because re-activating the agent puts it back into START state and restarts the event loop and if the agent had some attestation failure then it goes back into the FAILED state.

A better indicator is to check if the `severity_level` is `null`. For more information see here: https://keylime-docs.readthedocs.io/en/latest/rest_apis.html#cloud-verifier-cv

**Comment by kkaarreell** [comment]
I understand the request that system should not end up in a "trusted" GET_QUOTE state of it hasn't been proven correct beforehand. I make sense to me to have "untrusted GET_QUOTE" for not yet evaluated systems and another "trusted GET_QUOTE" for systems that were so far compliant.

**Comment by THS-on** [comment]
@kkaarreell `GET_QUOTE` and all the other states are mainly for the event loop and no longer intended to check if an attestation failure occurred. For this we now have the `severity_level` and `last_event_id`. Adding more states just complicates the event loop, without any real benefit.

This issue was opened before the failure tagging and severity level PR (https://github.com/keylime/keylime/pull/728) was merged.

**Comment by kkaarreell** [comment]
I see, I wasn't aware of that. Thank you.

**Comment by mpeters** [comment]
I agree with @THS-on on this one. `GET_QUOTE` shouldn't be used for trust-worthiness and we can close this issue.
