### ISSUE TITLE
[Discussion] Drop SPDX-License-Identifier header?

### ISSUE THREAD

**Issue by aplanas** [keylime/keylime#830]
I will like to discuss the drop of the `SPDX-License-Identifier` and the Copyritght holders headers in the Python code.  The `LICENSE` file should cover the common case, and the copyright notice can be in the documentation, or in some more general place.

**Comment by THS-on** [comment]
I like having the licence identifier directly in the file, because then there is no ambiguity when other files in a project might have different licences. 
Moving the copyright into a different file is fine for me because it does not make sense in most cases where multiple organisations now have worked on the same file.

**Comment by aplanas** [comment]
Multiple license can be an issue sometimes (there are some incompatibilities), but when this situation is present would make sense that the file can have its own SPDX header when is not the default one.

I agree with the second argument.

**Comment by mpeters** [comment]
I agree that pulling both into a single file would make sense and only have a separate license section for a file if it's different. But I'm pretty sure we would never want to have multiple licenses as not only are there incompatibilities, but it would make life very difficult for packagers.

I'm in favor of this change, but wanted to give it a couple of days to make sure there weren't any big objections from the community.

**Comment by aplanas** [comment]
I will do it!
